export const BAM = require('./BAM_icon/favicon-32x32.png')
export const FA = require('./FA_icon/favicon-32x32.png')
export const FQ = require('./FQ_icon/favicon-32x32.png')
export const GFF = require('./GFF_icon/favicon-32x32.png')
export const VCF = require('./VCF_icon/favicon-32x32.png')
export const FOLDER = require('./Folder_icon/file-solid.svg')
